spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "Songxiao123."
    url:  jdbc:mysql://10.0.0.40:3306/demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true

#mybatis:
#  mapper-locations:
#    - classpath:mapper/*.xml